[package]
name = "noun"
version = "0.1.0"
edition = "2021"
authors = ["Peter McEvoy <peter@tlon.io>"]

[features]
default = ["ibig"]
thread-safe = []
ibig = ["dep:ibig"]

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
ibig = { version = "0.3.6", optional = true }
